# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfe9195fd836ee68f2ffd8affe55eb84bf80436d84369d9fa13ba90784e2245816c3eb514f78a7e01d00ae1063e0a5b8d100ef3cbc038688bc57416e9831ebf5

test:
  secret_key_base: 35f519e557c58e0975ce75c1b9c5a0a835efb8b67274e865290553c5389e25d3d56ec01be3603c313836b3183547d8b1347b6151c4dbd706a624a945b52a56ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
